#! /bin/sh

if [ -z "$1" ]; then
    echo 'Usage:'
    echo '    $0 IP'
    exit 0
fi

IP="$1"
shift

ssh th@$IP '
    cd thingshappening
    ./env/bin/python manage.py shell -c "from thingshappening.utils import *; print(crop_old_events())"
'
