# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-22 17:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thingshappening', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='host',
            new_name='user',
        ),
    ]
