# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-22 17:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('thingshappening', '0002_auto_20180122_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 22, 17, 41, 42, 44126, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 22, 17, 42, 4, 337652, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
