# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-28 18:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thingshappening', '0003_auto_20180122_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image_url',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
