# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-03 06:45
from __future__ import unicode_literals

from django.db import migrations, models
import thingshappening.models


class Migration(migrations.Migration):

    dependencies = [
        ('thingshappening', '0004_event_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='end',
            field=models.DateTimeField(default=thingshappening.models.default_end),
        ),
        migrations.AlterField(
            model_name='event',
            name='start',
            field=models.DateTimeField(default=thingshappening.models.default_start),
        ),
    ]
